[package]
name = "playground"
version = "0.31.0"

[package.metadata.docs.rs]
all-features = true

[[bin]]
name = "playground"
path = "lib.rs"

[dependencies]
deno_ast = { path = "../deno_ast", features = ["bundler", "cjs", "codegen", "dep_graph", "module_specifier", "proposal", "react", "sourcemap", "transforms", "typescript", "view", "visit"] }

anyhow = { version = "1.0.64", optional = true }
base64 = { version = "0.13.1", optional = true }
deno_media_type = { version = "0.1.2", default-features = false }

dprint-swc-ext = "0.13.0"
serde = { version = "1.0.144", features = ["derive"] }
text_lines = { version = "0.6.0", features = ["serialization"] }
url = { version = "2.3.1", features = ["serde"], optional = true }

# swc's version bumping is very buggy and there will often be patch versions
# published that break our build, so we pin all swc versions to prevent
# pulling in new versions of swc crates
swc_atoms = "=0.6.0"
swc_common = "=0.33.0"
swc_config = { version = "=0.1.7", optional = true }
swc_config_macro = { version = "=0.1.2", optional = true }
swc_ecma_ast = { version = "=0.110.0", features = ["serde-impl"] }
swc_ecma_codegen = { version = "=0.146.3", optional = true }
swc_ecma_codegen_macros = { version = "=0.7.3", optional = true }
swc_ecma_dep_graph = { version = "=0.113.3", optional = true }
swc_ecma_loader = { version = "=0.45.0", optional = true }
swc_ecma_parser = "=0.141.3"
swc_ecma_transforms_base = { version = "=0.134.8", optional = true }
swc_ecma_transforms_classes = { version = "=0.123.8", optional = true }
swc_ecma_transforms_compat = { version = "=0.160.10", optional = true }
swc_ecma_transforms_macros = { version = "=0.5.3", optional = true }
swc_ecma_transforms_optimization = { version = "=0.195.8", optional = true }
swc_ecma_transforms_proposal = { version = "=0.168.12", optional = true }
swc_ecma_transforms_react = { version = "=0.180.11", optional = true }
swc_ecma_transforms_typescript = { version = "=0.185.8", optional = true }
swc_ecma_utils = { version = "=0.124.7", optional = true }
swc_ecma_visit = { version = "=0.96.0", optional = true }
swc_eq_ignore_macros = "=0.1.2"
swc_bundler = { version = "=0.222.13", optional = true }
swc_graph_analyzer = { version = "=0.22.0", optional = true }
swc_macros_common = { version = "=0.3.8", optional = true }
swc_trace_macro = { version = "=0.1.3", optional = true }
swc_visit = { version = "=0.5.7", optional = true }
swc_visit_macros = { version = "=0.5.8", optional = true }
